server:
  port: 9090
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://sslrmherfdwzbr:7ee9ca489f84ad663e8ff9117f9757020b546728db468ccc3940c085733be779@ec2-54-243-92-68.compute-1.amazonaws.com:5432/dburavluts9sp5
    username: sslrmherfdwzbr
    password: 7ee9ca489f84ad663e8ff9117f9757020b546728db468ccc3940c085733be779
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para a Semana DIO e Santander